2023-01-19 22:16:37 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:16:37 *** main.py *** start_flask() ~ Exception: (<class 'OSError'>, OSError(48, 'Address already in use'), <traceback object at 0x7f7b805508c0>)
2023-01-19 22:18:40 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:19:09 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:19:27 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:20:01 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:20:08 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:21:18 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:22:26 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:26:05 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:26:08 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:26:30 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:26:33 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:27:51 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:27:54 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:28:47 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:28:49 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:32:10 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
2023-01-19 22:32:13 *** main.py *** start_flask() ~ Flask running
2023-01-19 22:34:54 *** main.py *** __main__() ~ Exception (ID: <module 'signal' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/signal.py'>) has been caught. Cleaning up...
